-- Confirmed 2026-10-06: official prices, miao currency, one instance of each SKU per household.
update public.furniture_products p set price=v.price,currency='miao',purchase_limit=1,active=true
from (values
('lunar-bookshelf',180),
('lunar-desk',150),
('lunar-chair',60),
('lunar-tree',210),
('lunar-bed',90),
('lunar-window',90),
('lunar-rug',120),
('lunar-wall',150),
('lunar-floor',150),
('lunar-frame-landscape',45),
('lunar-frame-portrait',45),
('lunar-frame-square',45),
('wood-bookshelf',120),
('wood-desk',100),
('wood-chair',40),
('wood-tree',140),
('wood-bed',60),
('wood-window',60),
('wood-rug',80),
('wood-wall',100),
('wood-floor',100),
('wood-frame-landscape',30),
('wood-frame-portrait',30),
('wood-frame-square',30),
('royal-bookshelf',240),
('royal-desk',200),
('royal-chair',80),
('royal-tree',280),
('royal-bed',120),
('royal-window',120),
('royal-rug',160),
('royal-wall',200),
('royal-floor',200),
('royal-frame-landscape',60),
('royal-frame-portrait',60),
('royal-frame-square',60)
) v(sku,price) where p.sku=v.sku and not p.is_test;
